# Generated by Django 5.1.3 on 2025-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0004_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Natural', 'Persona Natural'), ('Juridico', 'Persona Jurídica')], default='Natural', max_length=10),
        ),
    ]
